### ISSUE TITLE
compute reduced chi-sq

### ISSUE THREAD

**Issue by mpfoster** [elihuihms/itcsimlib#4]
to facilitate model comparison, opt should compute the reduced chi-square (= chisq/(m_observations - n_params)

**Comment by elihuihms** [comment]
This behavior won't be added explicitly, since it's more generally useful to provide the non DoF-corrected chisq. However, the desired reduced chi-square can be readily calculated after a fit, using the experiments' .npoints attribute (this was fixed in commit 8d2bb61faf621cc03ebb153186be5177ffc90392 so that MSExperiments return the total number of datapoints, not just the number of titration points).

**Comment by mpfoster** [comment]
@elihuihms why not just report both? It may not be obvious to the naive user how to compute the red-chisq.
