### ISSUE TITLE
pyx in python 2.7?

### ISSUE THREAD

**Issue by mpfoster** [elihuihms/itcsimlib#5]
I tried the code  itcsimlib/examples/ising_plotter.py  but got an error about no pyx module. Tried installing with pip, but got an error:

`pip install pyx
Collecting pyx
  Using cached https://files.pythonhosted.org/packages/b4/a0/75d9d39bbd0bcd3aac7bf909b1c356188734a865552607a8c6bba3bf30bd/PyX-0.14.1.tar.gz
No files/directories in /private/var/folders/_2/qrb2t3393p37q5xp1c9fzxh40000gp/T/pip-install-T6f3Yr/pyx/pip-egg-info (from PKG-INFO)
`

Google search took me to https://github.com/mjg/PyX/blob/master/INSTALL, which reports that python >3.2 is needed. But, I thought you were using 2.7. Correct?

**Comment by mpfoster** [comment]
figured out how to install a 2.7-compatible version of pyx. Now it works!

**Comment by mpfoster** [comment]
OK, two more issues: 

1. The latex output doesn't seem to be in a logical order (at least for a tetramer: `4 K_{dGX} L + 4 K_{dGY}^{2} K_{dGZ} L^{3} + K_{dGZ}^{4} L^{4} + 2 L^{2} \left(K_{dGX}^{2} + 2 K_{dGY}^{2}\right) + 1`

2. For a 4-site circular, the plotter seems to incorrectly separate the states w/ 3 bound:
![image](https://user-images.githubusercontent.com/11504940/42172252-7c2eedd4-7de9-11e8-9c5c-eecd38c1fdcf.png)

**Comment by elihuihms** [comment]
I couldn't recreate the issue, but it's almost certainly a floating point comparison issue. In 7e679831435f4b0f69153b9b06cf1b09e26728cd degeneracy of configs is now determined based on the representation of the configuration's free energy, which will resolve that issue.

The order of the latex output cannot be changed, since it's a result of sympy's symbolic simplification of the PF. You'll have to order the terms by hand as desired, I suggest using a system of equations format for readability.
